// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Techi.Electronics.ProductAPI.Data;

#nullable disable

namespace Techi.Electronics.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Techi.Electronics.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Smartphones",
                            Description = "Apple iPhone 15 Pro with A17 Pro chip, 128GB storage, 6.1-inch Super Retina XDR display, and advanced triple-camera system.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple iPhone 15 Pro",
                            Price = 999.99000000000001
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Smartphones",
                            Description = "Samsung Galaxy S24 Ultra with Snapdragon processor, 200MP camera system, S-Pen support, and 6.8-inch Dynamic AMOLED display.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1199.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Audio",
                            Description = "Premium wireless headphones with industry-leading noise cancellation, up to 30 hours battery life, and crystal-clear audio.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Sony WH-1000XM5 Noise Cancelling Headphones",
                            Price = 399.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Laptops",
                            Description = "Dell XPS 13 ultrabook with Intel Core i7 processor, 16GB RAM, 512GB SSD, and stunning InfinityEdge display.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Dell XPS 13 Laptop",
                            Price = 1299.99
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Wearables",
                            Description = "Apple Watch Series 9 with advanced health monitoring, fitness tracking, always-on Retina display, and seamless iPhone integration.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Apple Watch Series 9",
                            Price = 399.99000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Accessories",
                            Description = "Advanced wireless mouse with ultra-fast scrolling, precision tracking, and customizable buttons designed for productivity.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Logitech MX Master 3S Wireless Mouse",
                            Price = 99.989999999999995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
