// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Techi.Electronics.CouponAPI.Data;

#nullable disable

namespace Techi.Electronics.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318032710_addCouponAndSeedTable")]
    partial class addCouponAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Techi.Electronics.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "SAVE10",
                            DiscountAmount = 10.0,
                            MinAmount = 100
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "TECH20",
                            DiscountAmount = 20.0,
                            MinAmount = 200
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "FREESHIP",
                            DiscountAmount = 15.0,
                            MinAmount = 75
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "BLACKFRIDAY",
                            DiscountAmount = 50.0,
                            MinAmount = 500
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "NEWUSER25",
                            DiscountAmount = 25.0,
                            MinAmount = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
